### ISSUE TITLE
Login doesn't support Google or Facebook authentication

### ISSUE THREAD

**Issue by just4brown** [luceralabs/WakeAndroid#1]

**Comment by just4brown** [comment]
Blocked. I need app IDs and secrets from the respective Wake developer accounts to support external authentication

**Comment by gregjesl** [comment]
@just4brown I tried to make you an admin for the Wakē Facebook developer account; I get the following error: "You are trying to add users that haven't verified their accounts. Tell Justin to go to the help center to complete the verification." 

I'm working on the developer account for Google.

**Comment by gregjesl** [comment]
@just4brown I've added your jbrown@luceralabs.com account to the Google API account.  @7200rpm I've made you an owner of the Google API account too.

**Comment by just4brown** [comment]
@gregjesl, I registered my facebook developer account, try adding me again. I was able to access the Google API account but I don't have permission to create new credentials. Can you make me an admin, or whatever is needed so that I can create a new client credential?

**Comment by gregjesl** [comment]
@just4brown Here's the error I'm still getting: 
<img width="529" alt="screen shot 2016-12-31 at 12 52 59 pm" src="https://cloud.githubusercontent.com/assets/14158889/21579228/73fc56d8-cf58-11e6-9f57-a9948d4812b5.png">

**Comment by gregjesl** [comment]
@just4brown I elevated your privileges in the Google API.  There is already a web client built for Auth0 titled "Web Client" in the Google API for Wakē though.

**Comment by just4brown** [comment]
@gregjesl, I'm at a loss for what to do with the facebook thing (maybe we should hop on hangouts soon and figure it out together?). I made some progress with the google authentication, but I can't get past a strange exeception when trying to authenticate through google: "An error occurred when trying to authenticate with the server", I'd like to look at the logs in our auth0 account, but it says I'm not an admin.
