### ISSUE TITLE
Secondary User Onboarding

### ISSUE THREAD

**Issue by gregjesl** [luceralabs/WakeAndroid#10]
If an unregistered Wakē user indicates that they want to associate their account with an existing Wakē, then they are a secondary user.  They should be presented with a screen that allows them to submit a code to associate their account. They should also be links to https://luceralabs.com/terms.html and https://luceralabs.com/privacy.html for the Terms & Conditions and Privacy Statement respectively.  There should also be a help button that triggers an email to help@luceralabs.com. 

When a user submits a code, the app should POST to /v1/users/code/{code} where {code} is the code they submitted.  No body is required for the POST call.  If the code is correct, the call will return the user's updated information derived from the primary user.  
![img_0009](https://cloud.githubusercontent.com/assets/14158889/21267700/53b9fd70-c360-11e6-8d53-41fa1adcb8ce.PNG)

**Comment by just4brown** [comment]
Code generation from primary user is working. Still need to test registration with code

**Comment by just4brown** [comment]
Tested. Registration successful. Works great
