### ISSUE TITLE
Implement timezone preference

### ISSUE THREAD

**Issue by just4brown** [luceralabs/WakeAndroid#5]

**Comment by gregjesl** [comment]
The Wakē API is configured to use timezones from the IANA database (https://www.iana.org/time-zones). Luckily this is what Android already uses natively (https://developer.android.com/reference/java/util/TimeZone.html). The timezone field of a user account should be the string name of the user's timezone.  For example, here in Log Angeles the proper string is "America/Los_Angeles".
